server {
    listen 80;
    
    # Standard SPA Shell
    location / {
        root /usr/share/nginx/html/shell;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # MFE1 Subpath
    location /mfe1/ {
        alias /usr/share/nginx/html/mfe1/;
        index index.html;
        try_files $uri $uri/ /mfe1/index.html;
    }

    # MFE2 Subpath
    location /mfe2/ {
        alias /usr/share/nginx/html/mfe2/;
        index index.html;
        try_files $uri $uri/ /mfe2/index.html;
    }
}
